[package]
name = "core-hex"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.clippy]
undocumented_unsafe_blocks = "forbid"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -2 }
